### ISSUE TITLE
DECIPHER %HI not available in gene info

### ISSUE THREAD

**Issue by holtgrewe** [varfish-org/annonars#393]
**Describe the bug**
The DECIPHER %HI score is not available in `gene_info` endpoint of server.

**To Reproduce**
1. Go to https://reev.cubi.bihealth.org/gene/BRCA1?genomeBuild=grch37
2. See that %HI is N/A

**Expected behavior**
The %HI should be displayed.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by xiamaz** [comment]
This has been fixed
