### ISSUE TITLE
Query for genome range with `grch38` returns `500` status code

### ISSUE THREAD

**Issue by gromdimon** [varfish-org/annonars#446]
**Describe the bug**
For a specific request (which seems to be valid), annonars returned 500 error.

**To Reproduce**
1. Try this url: https://reev.cubi.bihealth.org/internal/proxy/annonars/annos/range?genome_release=grch38&chromosome=17&start=80104789&stop=80119881
Or this url: https://reev.cubi.bihealth.org/internal/proxy/annonars/annos/range?genome_release=grch38&chromosome=17&start=123&stop=1234
Or this one: https://reev.cubi.bihealth.org/internal/proxy/annonars/annos/range?genome_release=grch38&chromosome=16&start=68829738&stop=68829999

**Expected behavior**
Either the request is invalid, or there're some problems with the annonars

**Additional context**
Data used in request:
Genome release: grch38
chromosome: 17
start: 80104789
stop: 80119881

Funny, that by changing genome release - everything worked.

Here is the response message:
```
problem decoding protobuf from database (cf_name=gnomad_nuclear_data): failed to decode Protobuf message: AgeInfo.age_hist_hom_bin_freq: Record.age_info: invalid wire type: ThirtyTwoBit (expected Varint)
```

**Comment by holtgrewe** [comment]
Fixed now. Note that this rolled out gnomad-genomes v4.1.
